import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "signature-linen-set",
    name: "Signature Linen Set",
    description: "A clean, minimalist product shot of a premium white linen duvet cover neatly folded. It sits alone against a seamless soft grey background, lit perfectly to show the natural wrinkles and breathability of the high-quality linen. The aesthetic is extremely high-end, focusing entirely on the materiality of the fabric without any distracting props.",
    price: 1250000,
    discount_percentage: 0,
    category: "sprei",
    colors: ["Pure White", "Warm Beige", "Soft Cream"],
    sizes: ["Queen", "King", "Extra King"],
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDBi9z0qRB9zLwFuEvIR2yrvxnnQisSLG6apDsB-q-7kGgYj5l98X4N5oXRYwRSEPhxbKNBAcHxqiHxA_i1FY-5VJBnyU5xVyoeUl--oGOnChEyVSjaqOyVNtKr8Otl-3tfXIhixa21TqO6CBQg3N9cd0HZ0HdMfQeESSrH3YDZy3lJeLQleY3X0-h9AjXzlU7M2Zy4A4Hgksg7yc-ZfHi020EVlm4TQtla8HnOAqjZMwyIeEnu823b"],
    material: "100% Fine Organic Linen",
    care_instructions: "Cuci dengan air dingin menggunakan putaran mesin cuci lambat. Jemur gantung.",
    stock: 12,
    sold_count: 55,
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "silk-blend-pillowcase",
    name: "Silk Blend Pillowcase",
    description: "A high-end product photograph of luxury silk-blend pillowcases in a muted champagne tone. Two pillowcases are styled perfectly plumped on a pristine white surface, bathed in bright, soft natural light that catches a subtle sheen on the fabric. The image exudes calm, sophisticated luxury, fitting seamlessly into an airy, gallery-like layout.",
    price: 450000,
    discount_percentage: 10,
    category: "aksesoris",
    colors: ["Champagne", "Pearl White", "Silver Grey"],
    sizes: ["Standard Size"],
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuB6FfEaZAD01EHxy4vX-vf46arYJ5fC291-jEknJ1w_XuVQSRMt7-Lpzy1EOOo2UigNTzsiXSjxpUESK6TAQfR547NbO0Y7HpBV4aYTtFqXbmj-akY0aI56cfB76yymzdwrmLemGd7Ao0OUeKqakrzwsRRCUgK8tXEVHW55PMeEXyXwLPqvFYnGH8bEKfRelxLYsXRSwFocu07M827-zueiTNHFL7B3WwtLiCZ5Gn23ZDXwagnssr-g"],
    material: "Mulberry Silk & Cotton Blend",
    care_instructions: "Cuci dengan deterjen sutra halus secara manual dengan tangan. Setrika dengan alas kain tambahan.",
    stock: 20,
    sold_count: 120,
    created_at: "2026-01-02T00:00:00.000Z",
    updated_at: "2026-01-02T00:00:00.000Z"
  },
  {
    id: "textured-cotton-throw",
    name: "Textured Cotton Throw",
    description: "A detailed macro shot focusing on the delicate stitching and textured hem of a premium cotton blanket in a soft, earthy clay color. The tight framing abstracts the product, turning the folds of the fabric into a soft, undulating landscape. The lighting is diffused and bright, maintaining a light-mode, minimalist design sensibility.",
    price: 850000,
    discount_percentage: 5,
    category: "selimut",
    colors: ["Earthen Clay", "Sage Green", "Slate Grey"],
    sizes: ["Double", "Queen"],
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDBZdq_JHASPweKA1qGuRniF0Nq7y0wAXUd7gQgkFLgzZdMJa6qTfQFlFl7b1NUfr8d5Md6aZPySve2h_YIhd_HH9kytrPHKirAzxyvy80pTsmbrZKArbySTyfYU_Rzvqfti62N-DrtXeAnMc6czSn2q-eWuaX3yDJ0VIInI6yAFo61i--aDfmW2H244D_leiWhxx_mw3bSimLBfMb1Hsw1Ye8gwQjk2353WPVEx0jZhAH7JEkeEOQG"],
    material: "100% Breathable Organic Cotton",
    care_instructions: "Mesin cuci putaran lembut, jemur mendatar untuk mencegah kerutan berlebih.",
    stock: 8,
    sold_count: 42,
    created_at: "2026-01-03T00:00:00.000Z",
    updated_at: "2026-01-03T00:00:00.000Z"
  },
  {
    id: "essential-bundle",
    name: "The Essential Bundle",
    description: "A sophisticated editorial image of a complete bedding bundle in a deep, moody charcoal grey, providing a striking contrast to a bright, minimalist white room setting. The bed is styled with relaxed elegance, showing layers of sheets, a duvet, and pillows. Soft, directional light highlights the premium weave of the fabric, ensuring the dark tones remain rich and detailed without feeling heavy.",
    price: 2100000,
    discount_percentage: 15,
    category: "bedcover",
    colors: ["Charcoal Grey", "Pebble Stone", "Mist White"],
    sizes: ["Queen", "King", "Extra King"],
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDMZ_wf8sbApFlgsxPQbCyCmH6hYvv3oPcqK3KeCbkmRsqhkuifkVmYLp9FoXcm4ML3rEWWX9z0c6pc0_63A7EgVurU3HpUYGjc34LLPrpNzxpRtknlRMfXX8HEZFcmU6xVWrkR_sOuTDrCj4hO5UanoNGQF84fzjOm1v8ErHbunhyZu4_aB8Sf9wbrZpC82_kXDrA67sK94h39oOAlvFwNSQjNCWjKb03wlB1KMXwJ2laumH7TBBjx"],
    material: "100% Long-Staple Egyptian Cotton",
    care_instructions: "Dapat dicuci dengan mesin cuci normal, gunakan air hangat atau sedang.",
    stock: 5,
    sold_count: 95,
    created_at: "2026-01-04T00:00:00.000Z",
    updated_at: "2026-01-04T00:00:00.000Z"
  }
];
